### ISSUE TITLE
[BUG] Auth Groups block incoming requests with valid auth

### ISSUE THREAD

**Issue by jhoogstraat** [Apodini/corvus#27]
**Describe the bug**
I am getting User not authenticated with auth groups.

**To Reproduce**
Just
```swift
BasicAuthGroup<User>("login") {
    Custom<String>(type: .get) { req in
        req.eventLoop.makeSucceededFuture("Test")
    }
}
```
**Expected behavior**
User should be authenticated.

**Environment:**
 - Swift Version: 5.2
 - Xcode Version: 11.4.1
 - Corvus Version: develop branch
 - Database driver Version: Fluent SQLite Driver

**Additional context**
Works, if order is inverted:
```swift
let guardedRoutesBuilder = groupedRoutesBuilder.grouped([
    T.authenticator(),
    T.guardMiddleware()
])
```

**Comment by bmikaili** [comment]
Strange, didn't we have a case where the order had to be literally the other way around to work?
