### ISSUE TITLE
[FEATURE] Implement Mediator types

### ISSUE THREAD

**Issue by jhoogstraat** [Apodini/corvus#3]
## Problem
It may not be desirable to always use `CorvusModel` for decoding the body of certain requests, like create or update requests. 

## Solution
To have more control over what the user is able to provide in a request body 'mediator', or 'carrier' types can be used.
These types are also refered to as 'Data Transfer Objects' or DTOs.
These can be implemented as DTOModifiers and ResponseModifier.

## Alternative Solutions
Altering Create and Update endpoint to support these operations.
Altering CorvusModel to inherit this functionality.

**Comment by bmikaili** [comment]
I agree this is needed. I haven't figured out a way to solve this generically yet. I struggle to find a way to do it generically in `CorvusModel` itself. We may have to resort to how you did it in your pull request, where developers will have to manually extend their models.

**Comment by jhoogstraat** [comment]
My solution requires no changes to existing code, because by default nothing changes. By default the `CorvusModel` itself is used to decode create/update requests, just like before.

What do you have in mind? Somehow the developer has to tell the system, which properties to decode, no?

**Comment by bmikaili** [comment]
Yeah you're right. Currently in Swift there is probably no other way. If there was a way to iterate over the properties of a struct that implements a protocol it would be possible to do generically, but that's not something that can be done in Swift.

**Comment by PSchmiedmayer** [comment]
We will archive Corvus in favor of [Apodini](https://github.com/Apodini/Apodini) as a worthy successor.
