### ISSUE TITLE
[BUG] Cannot build on Linux because LinuxMain.swift is missing

### ISSUE THREAD

**Issue by jhoogstraat** [Apodini/corvus#34]
**Describe the bug**
swift build fails because there is no LinuxMain.swift in the Test directory.

**To Reproduce**
Run swift build on Linux

**Expected behavior**
Corvus should be built successfully

**Environment (enter your versions):**
 - Swift Version: 5.2.2
 - Xcode Version: -
 - Corvus Version: Head

**Comment by PSchmiedmayer** [comment]
@jhoogstraat I would suggest that we do something similar to the Swift Argument parser: https://github.com/apple/swift-argument-parser/blob/master/Tests/LinuxMain.swift
Pointing the developers to `swift test --enable-test-discovery` is a good idea in my opinion.

**Comment by bmikaili** [comment]
Is it necessary to add `--enable-test-discovery` to `swift build` as well? I thought adding it to `swift test` gets rid of the error.

**Comment by PSchmiedmayer** [comment]
@bmikaili The flag also seems to be available for `swift build` so I would also add it there too.

**Comment by PSchmiedmayer** [comment]
@bmikaili I would suggest that we also add a GitHub workflow that runs a build and test on every commit on a linux build agent so we cover macOS and Linux in your build pipeline 👍 ... what do you think?

**Comment by bmikaili** [comment]
We could do that, but I'm not sure if that wouldn't be redundant as Vapor already tests for Linux. And if Vapor runs on Linux, so does Corvus.

**Comment by PSchmiedmayer** [comment]
Vapor does already tests building for Linux but we might use some code, e.g. from Foundation that is not implemented on Linux but is available on macOS as Foundation is still missing some functionality on Linux. And we would be able to catch the described test issue that would be caught if we continuously and automatically test building on Linux too 👍

**Comment by bmikaili** [comment]
Makes sense. Added the respective workflows.

**Comment by PSchmiedmayer** [comment]
Nice, thank you! 👍
