### ISSUE TITLE
[FEATURE] GuardGroup to allow for basic authorization

### ISSUE THREAD

**Issue by jhoogstraat** [Apodini/corvus#39]
**Is your feature request related to a problem? Please describe.**
A new Type `GuardGroup` could be used to allow for the authorization of requests.
This would allow a simple Role system, where each role has different access levels.

**Describe the solution you'd like**
Implement a new Group called `GuardGroup` which takes an array of `Guard` instances.
A `Guard` is responsible for evaluating if the user is authorized to access the endpoint.

**Describe alternatives you've considered**
All other group types could get a new parameter `guards: Guard...`.

**Comment by PSchmiedmayer** [comment]
We will archive Corvus in favor of [Apodini](https://github.com/Apodini/Apodini) as a worthy successor.
