### ISSUE TITLE
[FEATURE] Allow authentication via JWTs

### ISSUE THREAD

**Issue by jhoogstraat** [Apodini/corvus#40]
**Is your feature request related to a problem? Please describe.**
I'd like to authenticate a User via a JWT that contains a payload.

**Describe the solution you'd like**
Implement a `JWTAuthGroup` that authenticates a JWT and injects it into req.auth.
A `CorvusJWTAuthenticator` can be used to seperate the authentication from the group type.

**Comment by jhoogstraat** [comment]
Maybe this fits better in a separate package (like corvus-jwt) as this is not a core functionality and requires to have the jwt-kit and jwt dependencies from Vapor.

**Comment by bmikaili** [comment]
Hmm, I'm not sure. I think if we want to go with a batteries-included approach, we can just include everything in Corvus, even if that makes the package size quite large. @PSchmiedmayer what do you think?

**Comment by PSchmiedmayer** [comment]
@bmikaili @jhoogstraat I generally think that having everything in Corvus so far makes sense. One dependency that support all the functionality. 
What about making it a separate target that is exported as a separate product? So you only have to import Corvus as a dependency but only if you include the target you have to build the JWT package. Then we also don't have to maintain two separate project and you can always test all the functionality in one repo 👍

**Comment by PSchmiedmayer** [comment]
We will archive Corvus in favor of [Apodini](https://github.com/Apodini/Apodini) as a worthy successor.
